// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Util$ReasonTree = require("./Util.bs.js");

Util$ReasonTree.printDir(0, "node_modules", "../");

/*  Not a pure module */
